name: deployment_trial_2
on: 
 push:
   branches:
         - main
         - master
 workflow_dispatch: null
jobs:
   deployment_local_server:
                      runs-on: ubuntu-latest
                      steps: 
                          - name: download-npm
                            uses: actions/setup-node@v4
                            
                            

               
       
