name: deployment_trial_2
on: 
 push:
   branches:
         - main
         - master
 workflow_dispatch: null
jobs:
   deployment_local_server:
                      runs-on: ubuntu-latest
                      steps: 
                          - name: log
                            run: echo "Downloading nodejs..."
                          - name: download-npm
                            uses: actions/setup-node@v4
                        
   deployment_to_production_server:
                      runs-on: ubuntu-latest
                      steps: 
                          - name: log
                            run: echo "Downloading nodejs..."
                          - name: download-npm
                            uses: actions/setup-node@v4  
                          - name: install_dependencies
                            run: npm ci
                          - name: start_app
                          - run : npm start

                          

               
       
